name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: linux-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            suffix: windows-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            suffix: darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test-quick

      - name: Get version info
        id: version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          VERSION: ${{ steps.version.outputs.VERSION }}
          BUILD_TIME: ${{ steps.version.outputs.BUILD_TIME }}
          GIT_COMMIT: ${{ steps.version.outputs.GIT_COMMIT }}
        shell: bash
        run: |
          # Build using Makefile
          make build
          
          # Rename binary to platform-specific name
          BINARY_NAME="lai-${{ matrix.suffix }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          
          mv lai "${BINARY_NAME}"

      - name: Create archive
        shell: bash
        run: |
          BINARY_NAME="lai-${{ matrix.suffix }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          
          tar -czf "lai-${{ matrix.suffix }}.tar.gz" "${BINARY_NAME}" README.md LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lai-${{ matrix.suffix }}
          path: lai-${{ matrix.suffix }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get version info
        id: version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/lai-linux-amd64/*.tar.gz
            artifacts/lai-windows-amd64/*.tar.gz
            artifacts/lai-darwin-amd64/*.tar.gz
            artifacts/lai-darwin-arm64/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}