name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: make deps

      - name: Set script permissions
        run: chmod +x scripts/*.sh

      - name: Run tests
        run: make test-quick
